events {
    worker_connections 1024;
}

http {
    upstream minio_s3 {
        server minio:9000;
    }

    server {
        listen 80;
        server_name localhost;

        # Проксирование только запросов к изображениям
        location /images/ {
            proxy_pass http://minio_s3/images/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Для больших файлов
            client_max_body_size 100M;
            proxy_buffering off;
            proxy_request_buffering off;
        }

        # Остальные запросы возвращают 404
        location / {
            return 404;
        }
    }
}