// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@cavi.local"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cavi-calculations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список заявок (кроме удалённых и черновиков) с фильтрацией по статусу и диапазону дат формирования.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculations"
                ],
                "summary": "Список заявок",
                "parameters": [
                    {
                        "enum": [
                            "formed",
                            "completed",
                            "rejected"
                        ],
                        "type": "string",
                        "description": "Фильтр по статусу",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"2025-01-01\"",
                        "description": "Дата формирования от (YYYY-MM-DD)",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"2025-12-31\"",
                        "description": "Дата формирования до (YYYY-MM-DD)",
                        "name": "date_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список заявок",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.CalculationResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cavi-calculations/draft": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает ID черновика заявки текущего пользователя и количество групп в нём.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculations"
                ],
                "summary": "Корзина (черновик)",
                "responses": {
                    "200": {
                        "description": "Информация о корзине",
                        "schema": {
                            "$ref": "#/definitions/handler.CartIconResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cavi-calculations/draft/form": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Переводит черновик в статус \"сформирована\". Проверяет наличие групп в заявке. Устанавливает дату формирования.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculations"
                ],
                "summary": "Сформировать заявку",
                "responses": {
                    "200": {
                        "description": "Заявка сформирована",
                        "schema": {
                            "$ref": "#/definitions/handler.CalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Нет групп в заявке",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Черновик не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cavi-calculations/draft/groups": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет индекс CAVI для группы в заявке-черновике текущего пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculation-groups"
                ],
                "summary": "Обновить группу в черновике",
                "parameters": [
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.DraftGroupUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Группа обновлена",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные или черновик не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет группу из заявки-черновика текущего пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculation-groups"
                ],
                "summary": "Удалить группу из черновика",
                "parameters": [
                    {
                        "description": "ID группы",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.DraftGroupDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Группа удалена",
                        "schema": {
                            "$ref": "#/definitions/handler.DraftGroupResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный ID или группа не найдена в черновике",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cavi-calculations/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает детальную информацию о заявке, включая все группы в её составе.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculations"
                ],
                "summary": "Получить заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о заявке",
                        "schema": {
                            "$ref": "#/definitions/handler.CalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный ID",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Заявка не найдена",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет поля заявки: систолическое/диастолическое давление, скорость пульсовой волны.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculations"
                ],
                "summary": "Обновить заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CalculationUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Заявка обновлена",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Мягкое удаление заявки-черновика. Доступно только создателю заявки. Удаляет связи с группами.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculations"
                ],
                "summary": "Удалить заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Заявка удалена",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный ID или заявка не является черновиком",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Заявка не найдена",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cavi-calculations/{id}/moderate": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Завершает или отклоняет сформированную заявку. Доступно только модераторам. При завершении устанавливается количество групп.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculations"
                ],
                "summary": "Модерировать заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Действие модератора",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ModerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Заявка обработана",
                        "schema": {
                            "$ref": "#/definitions/handler.CalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные или статус заявки",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется роль модератора",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Заявка не найдена",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cavi-groups": {
            "get": {
                "description": "Возвращает список всех групп пациентов с возможностью фильтрации по названию, возрастной группе и типу заболевания.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Список групп",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поиск по названию (частичное совпадение)",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "young",
                            "middle",
                            "elderly"
                        ],
                        "type": "string",
                        "description": "Фильтр по возрастной группе",
                        "name": "age_group",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "diabetes",
                            "hypertension"
                        ],
                        "type": "string",
                        "description": "Фильтр по типу заболевания",
                        "name": "disease_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список групп",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.GroupResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт новую группу пациентов. Доступно только модераторам.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Создать группу",
                "parameters": [
                    {
                        "description": "Данные новой группы",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.GroupCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Группа создана",
                        "schema": {
                            "$ref": "#/definitions/handler.GroupResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется роль модератора",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cavi-groups/{id}": {
            "get": {
                "description": "Возвращает детальную информацию о группе пациентов по её ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Получить группу",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID группы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о группе",
                        "schema": {
                            "$ref": "#/definitions/handler.GroupResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный ID",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Группа не найдена",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет данные группы пациентов. Доступно только модераторам.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Обновить группу",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID группы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.GroupUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Группа обновлена",
                        "schema": {
                            "$ref": "#/definitions/handler.GroupResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется роль модератора",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Мягкое удаление группы (is_deleted = true). Также удаляет изображение. Доступно только модераторам.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Удалить группу",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID группы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Группа удалена",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный ID",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется роль модератора",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cavi-groups/{id}/add-to-draft": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Добавляет группу в заявку-черновик текущего пользователя. Если черновика нет — создаёт новый.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Добавить в черновик",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID группы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Группа добавлена в черновик",
                        "schema": {
                            "$ref": "#/definitions/handler.AddToDraftResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный ID или группа уже в черновике",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cavi-groups/{id}/image": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Загружает или заменяет изображение группы. Доступно только модераторам.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Загрузить изображение",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID группы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Файл изображения (JPEG, PNG)",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Изображение загружено",
                        "schema": {
                            "$ref": "#/definitions/handler.ImageUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется роль модератора",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Аутентифицирует пользователя и возвращает JWT токены (access + refresh).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Вход",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный вход",
                        "schema": {
                            "$ref": "#/definitions/handler.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учётные данные",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Добавляет access токен в blacklist Redis и удаляет refresh токен.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Выход",
                "responses": {
                    "200": {
                        "description": "Успешный выход",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает информацию о текущем авторизованном пользователе.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Текущий пользователь",
                "responses": {
                    "200": {
                        "description": "Данные пользователя",
                        "schema": {
                            "$ref": "#/definitions/handler.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет username и/или пароль текущего пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Обновить профиль",
                "parameters": [
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UserUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Профиль обновлён",
                        "schema": {
                            "$ref": "#/definitions/handler.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные или username занят",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется аутентификация",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/refresh": {
            "post": {
                "description": "Обновляет access и refresh токены по валидному refresh токену.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Обновить токены",
                "parameters": [
                    {
                        "description": "Refresh токен",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Новые токены",
                        "schema": {
                            "$ref": "#/definitions/handler.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Невалидный или истёкший refresh токен",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Создаёт нового пользователя в системе. Пароль хешируется с помощью bcrypt.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Регистрация",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь создан",
                        "schema": {
                            "$ref": "#/definitions/handler.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные или пользователь существует",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.AddToDraftResponse": {
            "description": "ID заявки-черновика",
            "type": "object",
            "properties": {
                "calculation_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.CalculationGroupResponse": {
            "description": "Информация о группе в составе заявки",
            "type": "object",
            "properties": {
                "cavi_index": {
                    "type": "number",
                    "example": 7.5
                },
                "group": {
                    "$ref": "#/definitions/handler.GroupResponse"
                },
                "group_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.CalculationResponse": {
            "description": "Полная информация о заявке на расчёт CAVI",
            "type": "object",
            "properties": {
                "calculation_groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.CalculationGroupResponse"
                    }
                },
                "creator_login": {
                    "type": "string",
                    "example": "user1"
                },
                "date_completed": {
                    "type": "string",
                    "example": "2025-01-15T12:00:00Z"
                },
                "date_created": {
                    "type": "string",
                    "example": "2025-01-15T10:30:00Z"
                },
                "date_formed": {
                    "type": "string",
                    "example": "2025-01-15T11:00:00Z"
                },
                "diastolic_pressure": {
                    "type": "integer",
                    "example": 80
                },
                "groups_count": {
                    "type": "integer",
                    "example": 3
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "moderator_login": {
                    "type": "string",
                    "example": "moderator1"
                },
                "pulse_wave_velocity": {
                    "type": "number",
                    "example": 8.5
                },
                "status": {
                    "type": "string",
                    "example": "draft"
                },
                "systolic_pressure": {
                    "type": "integer",
                    "example": 120
                }
            }
        },
        "handler.CalculationUpdateRequest": {
            "description": "Данные для обновления полей заявки (давление, скорость пульсовой волны)",
            "type": "object",
            "properties": {
                "diastolic_pressure": {
                    "type": "integer",
                    "example": 80
                },
                "pulse_wave_velocity": {
                    "type": "number",
                    "example": 8.5
                },
                "systolic_pressure": {
                    "type": "integer",
                    "example": 120
                }
            }
        },
        "handler.CartIconResponse": {
            "description": "Информация о черновике заявки пользователя",
            "type": "object",
            "properties": {
                "calculation_id": {
                    "type": "integer",
                    "example": 1
                },
                "items": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "handler.DraftGroupDeleteRequest": {
            "description": "ID группы для удаления из черновика заявки",
            "type": "object",
            "required": [
                "group_id"
            ],
            "properties": {
                "group_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.DraftGroupResponse": {
            "description": "ID заявки-черновика после операции",
            "type": "object",
            "properties": {
                "calculation_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.DraftGroupUpdateRequest": {
            "description": "Данные для обновления группы в черновике (индекс CAVI)",
            "type": "object",
            "required": [
                "group_id"
            ],
            "properties": {
                "cavi_index": {
                    "type": "number",
                    "example": 7.5
                },
                "group_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.ErrorResponse": {
            "description": "Стандартный ответ с ошибкой",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "invalid input"
                },
                "status": {
                    "type": "string",
                    "example": "fail"
                }
            }
        },
        "handler.GroupCreateRequest": {
            "description": "Данные для создания новой группы пациентов",
            "type": "object",
            "required": [
                "age_group",
                "name"
            ],
            "properties": {
                "age_group": {
                    "type": "string",
                    "enum": [
                        "young",
                        "middle",
                        "elderly"
                    ],
                    "example": "young"
                },
                "description": {
                    "type": "string",
                    "example": "Эластичные сосуды с низким уровнем жесткости"
                },
                "disease_type": {
                    "type": "string",
                    "enum": [
                        "diabetes",
                        "hypertension"
                    ],
                    "example": "diabetes"
                },
                "name": {
                    "type": "string",
                    "example": "Молодые пациенты"
                }
            }
        },
        "handler.GroupResponse": {
            "description": "Информация о группе пациентов",
            "type": "object",
            "properties": {
                "age_group": {
                    "type": "string",
                    "example": "young"
                },
                "description": {
                    "type": "string",
                    "example": "Эластичные сосуды с низким уровнем жесткости"
                },
                "disease_type": {
                    "type": "string",
                    "example": "diabetes"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image_url": {
                    "type": "string",
                    "example": "http://localhost:9000/cavi-images/diagrams/1.jpg"
                },
                "is_deleted": {
                    "type": "boolean",
                    "example": false
                },
                "is_selected": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "Молодые пациенты (до 35 лет)"
                }
            }
        },
        "handler.GroupUpdateRequest": {
            "description": "Данные для обновления группы пациентов",
            "type": "object",
            "properties": {
                "age_group": {
                    "type": "string",
                    "enum": [
                        "young",
                        "middle",
                        "elderly"
                    ],
                    "example": "middle"
                },
                "description": {
                    "type": "string",
                    "example": "Обновлённое описание"
                },
                "disease_type": {
                    "type": "string",
                    "enum": [
                        "diabetes",
                        "hypertension"
                    ],
                    "example": "hypertension"
                },
                "is_selected": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Обновлённое название"
                }
            }
        },
        "handler.ImageUploadResponse": {
            "description": "URL загруженного изображения",
            "type": "object",
            "properties": {
                "image_url": {
                    "type": "string",
                    "example": "http://localhost:9000/cavi-images/diagrams/1.jpg"
                }
            }
        },
        "handler.LoginResponse": {
            "description": "Токены и информация о пользователе после входа",
            "type": "object",
            "properties": {
                "is_moderator": {
                    "type": "boolean",
                    "example": false
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "username": {
                    "type": "string",
                    "example": "user1"
                }
            }
        },
        "handler.ModerateRequest": {
            "description": "Действие модератора над заявкой",
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "complete",
                        "reject"
                    ],
                    "example": "complete"
                }
            }
        },
        "handler.RefreshRequest": {
            "description": "Refresh токен для получения новой пары токенов",
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "handler.SuccessResponse": {
            "description": "Стандартный успешный ответ",
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "handler.UserLoginRequest": {
            "description": "Данные для входа в систему",
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "username": {
                    "type": "string",
                    "example": "user1"
                }
            }
        },
        "handler.UserRegisterRequest": {
            "description": "Данные для регистрации нового пользователя",
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "newuser"
                }
            }
        },
        "handler.UserResponse": {
            "description": "Информация о пользователе",
            "type": "object",
            "properties": {
                "is_moderator": {
                    "type": "boolean",
                    "example": false
                },
                "username": {
                    "type": "string",
                    "example": "user1"
                }
            }
        },
        "handler.UserUpdateRequest": {
            "description": "Данные для обновления профиля пользователя",
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "newpassword123"
                },
                "username": {
                    "type": "string",
                    "example": "newusername"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT токен в формате: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "CAVI Calculator API",
	Description:      "API для расчёта индекса CAVI (Cardio-Ankle Vascular Index).\nСистема позволяет управлять группами пациентов, создавать заявки на расчёт,\nдобавлять группы в заявки и проводить модерацию.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
